
# specificy directories
raw_reads_directory: '/mnt/md0/guinea_worm/ena_downloads/ena_all/'
output_directory: '/mnt/md0/guinea_worm/ngs_analyses/unmatched/mt'
metadata_file: '/mnt/md0/guinea_worm/ngs_analyses/gw_enaChadMIT.txt'

# specify parameters for TrimGalore -- automatically chcecks the adapter type
trim_galore:
  quality:  20    # default value
  min_read_length: 30   # this is dependent on the technology used, most NGS is 100-150 so min of 30 is generous for throwing out reads

reference_alignment:
  genome_name: 'DmedinensisMitochondrionComplete.fasta' # include extension
  genome_path: '/mnt/md0/guinea_worm/public_genomesGW/mt'


variant_calling:
  ploidy: 1     # the genome ploidy of the reference organism.

# following recommendations from GATK for hard filters.
# https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set
variant_filter:
  quality_depth: 2.0
  fisher_strand: 60.0
  mapping_quality: 40.0
  mapping_rootsq: -12.5
  mapping_rank: -8.0
  # final call set
  read_depth_min: 10.0
  rank_sum: 3.1

# snakemake -s ngs_preprocessing.snakefile --configfile ngs_analyses/configGW_mtAll.yaml --config iteration='2' --rerun-incomplete --jobs 100 --keep-going -np --latency-wait 30  | grep jointGenotype
