# config file for the GW ngs pipeline 

# output all results here
output_directory: '/home/bsiranos/idm_local/durrant_data/processing_small'

# metadata file that defines all information about samples. Tab delimited
# with the following columns. Forwrad and reverse sequencing reads should 
# be specified in the fq1 and fq2 columns, and all must follow the same paired-end 
# read specificaiton. 
# 'ena_accession', 'sample', 'unit', 'fq1', 'fq2', 'host', 'country', 'variant.data'
# an example is located on github
metadata_file: '/home/bsiranos/idm_local/durrant_data/metadata_small.tsv'

# specify parameters for TrimGalore -- automatically chcecks the adapter type
trim_galore:
  quality:  20    # default value
  min_read_length: 30   # this is dependent on the technology used, most NGS is 100-150 so min of 30 is generous for throwing out reads

# reference file for alignment - should be .fasta
reference_file: '/home/bsiranos/idm_local/references/d_medinensis_mitochondrion.fasta'

variant_calling:
  ploidy: 1     # the genome ploidy of the reference organism.

# following recommendations from GATK for hard filters.
# https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set
variant_filter:
  quality_depth: 2.0
  fisher_strand: 60.0
  mapping_quality: 40.0
  mapping_rootsq: -12.5
  mapping_rank: -8.0
  # final call set
  read_depth_min: 10.0
  rank_sum: 3.1

# Fasta file containing names and Primer information 
primer_file: '/home/bsiranos/idm_local/dropbox_data/pipeline_files/GWmtDNANGSprimers_v1.0_seqkit.fa'

# maximum number of iterations for base quality score recalibration 
max_iter: 2
