# Configuration file for nextstrain pipeline
# specify inputs and options here. 

################################################################################
# output directory
output_dir: "/mnt/data/guinea_worm/nextstrain"

################################################################################
# diploid_vcf: The VCF output of the variant calling pipeline with a ploidy of 2
# to run the pipleine several vcf files in a single directory, use the diploid_dir option instead
# expects file naming {BATCH_NAME}_jointGenotypeFiltered.vcf.gz from the processing pipeline
diploid_vcf: ""
diploid_dir: "/mnt/data/guinea_worm/nextstrain/original_vcf"

# filtering parameters for excluding samples and sites 
# max missing parameters are on a proportional scale of 0 to 1
# heterozygous proportion will be applied to the dominant allele
vcf_filter:
  site_max_missing: 0.1
  samp_max_missing: 0.5
  genotype_min_read: 5
  het_proportion: 1

################################################################################
# meta_file: metadata about each sample
# TAB DELIMITED file with the same sample names as in the vcf file above, each sample as a single now
# at minimum requires the following columns (not case senstive):
# sample, GPS_E, GPS_N, host, year
metadata: "/mnt/data/guinea_worm/metadata/mtDNA_NGS_Metadata_2021.11.04_msGroups.tsv"

################################################################################
# Nextstrain object building options

# ref_file: fasta file reference
reference_file: "/mnt/data/guinea_worm/public_genomesGW/mt/DmedinensisMitochondrionComplete.fasta"

# tree building method
# chose from iqtree, raxml, fasttree
tree_method: "iqtree"

# auspice_config_file: taken from the github repository, in the same folder as 
# nextstrain.snakefile. This defines what metadata is presented with the tree,
auspice_config_file: "auspice_config.json"
base_readme: "base_description.md"


