# Configuration file for nextstrain pipeline
# specify inputs and options here. 
# Note: to create a haploid VCF from the joint variant calling pipeline, run the set-up portion of the analyses manifest scripts file. 
# The analyses manifest file creates the haploid VCF, filter summary file, and the barcode groupings required to run this pipeline

################################################################################
# Project directory for all analyses. Assumes that each sequencing batch 
project_dir: "/mnt/data/guinea_worm/analyses/test"

# output directory
output_dir: "/mnt/data/guinea_worm/nextstrain"

################################################################################
# input diploid VCF from processing pipeline
diploid_vcf: "/mnt/data/guinea_worm/processing/vcf_files/batch_Feb012024_jointGenotypeFiltered.vcf.gz"

# filtering parameters for excluding samples and sites 
# max missing parameters are on a proportional scale of 0 to 1
# heterozygous proportion will be applied to the dominant allele
vcf_filter:
  site_max_missing: 0.5
  samp_max_missing: 0.5
  genotype_min_read: 5
  het_proportion: 1
  missing_barcode_max: 0.1

################################################################################
# meta_file: metadata about each sample
# TAB DELIMITED file with the same sample names as in the vcf file above, each sample as a single now
# at minimum requires the following columns (not case sensitive):
# sample, GPS_E, GPS_N, host, year
metadata: "/mnt/data/guinea_worm/metadata/GenomicSamplesMetadata_Database_v3.1_231006.txt"


################################################################################
# Nextstrain object building options
# ref_file: fasta file reference
reference_file: "/mnt/data/guinea_worm/public_genomesGW/mt/DmedinensisMitochondrionComplete.fasta"

# tree building method
# chose from iqtree, raxml, fasttree
tree_method: "iqtree"

# auspice_config_file: taken from the github repository, in the same folder as 
# nextstrain.snakefile. This defines what metadata is presented with the tree,
auspice_config_file: "auspice_config.json"
base_readme: "base_description.md"


